export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const FILTER_CREATED = "FILTER_CREATED";
export const FILTER_BY_TYPES = "FILTER_BY_TYPES";
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK';
export const GET_POKEMON_TYPES = 'GET_POKEMON_TYPES';
export const POST_POKEMON = 'POST_POKEMON';
export const CLEAR_POKEMONS_FILTERS = 'CLEAR_POKEMONS_FILTERS';


