export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK';
export const GET_POKEMON_TYPES = 'GET_POKEMON_TYPES';
export const POST_POKEMON = 'POST_POKEMON';
export const DELETE_CARD = 'DELETE_CARD';


